const KEY='xei.ed.premiere.v3';
const scenes=['opening','assessment','mri','origin','manual','contribution','propagate','reveal','summary','close'];
const manuals={
'XBM-101':{title:'BDC Agent Field Guide',section:'Customer Conversation Standard',lines:['Understand before persuading.','Reduce pressure, clarify intent, educate accurately, and earn the next step.','Capture the customer objective, concern, timeframe, decision-makers, and agreed follow-up.','Never trade truth for momentum.']},
'XBM-102':{title:'BDC Manager Operating Manual',section:'Coaching & Quality Standard',lines:['Coach observable behaviours, not personality.','Review whether the representative listened, clarified, educated, confirmed, and documented.','Turn repeated friction into training improvement.','Escalate uncertainty before it becomes customer harm.']},
'XBM-103':{title:'BDC Objection Playbook',section:'“I’m Just Looking”',lines:['Listen without interrupting.','Acknowledge without pressure.','Clarify what the customer hopes to learn.','Educate with the smallest useful amount of accurate information.','Offer a useful next step and let the customer choose.']},
'XBM-104':{title:'BDC Script Playbook',section:'Approved Customer Language',lines:['“Absolutely. What are you hoping to learn while you look?”','“I can give you a useful starting point without putting pressure on you.”','“Would it help to compare styles, budget ranges, or the project process first?”']}}
const defaults={scene:0,voice:true,answer:'',contribution:'',manual:'XBM-103'};let state={...defaults,...JSON.parse(localStorage.getItem(KEY)||'{}')};
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
function britishVoice(){const vs=speechSynthesis.getVoices();return vs.find(v=>/en-GB/i.test(v.lang)&&/female|serena|samantha|kate|moira|fiona|victoria|susan/i.test(v.name))||vs.find(v=>/en-GB/i.test(v.lang))||vs[0]}
function speak(t){if(!state.voice||!t||!('speechSynthesis'in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.voice=britishVoice();u.lang='en-GB';u.rate=.9;u.pitch=1.02;u.volume=.92;speechSynthesis.speak(u)}
const btn=(t,id='next',c='primary')=>`<button class="btn ${c}" id="${id}">${t}<span>→</span></button>`;
const shell=(k,t,b,a='')=>`<section class="scene"><div class="kicker">${k}</div><h1>${t}</h1>${b}<div class="actions">${a}</div></section>`;
function manual(id){const m=manuals[id];return `<div class="manual"><aside><div class="micro">LIVING DOCUMENT RUNTIME</div><h3>${m.title}</h3><input id="search" placeholder="Search the operating knowledge"><div class="tabs">${Object.keys(manuals).map(k=>`<button data-manual="${k}" class="${k===id?'active':''}">${k}</button>`).join('')}</div><p>Canonical · Governed · Searchable<br>Training, coaching and QA connected</p></aside><article><div class="micro">${id} · ${m.section}</div><h2>${m.section}</h2><div class="live"><i></i> LIVE OPERATING KNOWLEDGE</div>${m.lines.map((x,i)=>`<div class="line" data-search="${esc(x.toLowerCase())}"><b>${String(i+1).padStart(2,'0')}</b><span>${esc(x)}</span></div>`).join('')}</article></div>`}
function render(){speechSynthesis?.cancel();let h='',n='';const s=scenes[state.scene];
if(s==='opening'){h=shell('Private Executive Premiere','Ed, this began inside your company.',`<div class="hero"><div class="monogram">X</div><div><p class="lead">You created the first real BDC department for Checkmate Holding Group in Panama. Vianka and five new agents needed to inherit cabinet and countertop knowledge immediately.</p><p class="truth">CHECKMATE HOLDING GROUP · OWNED BY EDWARD<br>DARREN · SYSTEM ARCHITECT AND SALES LEADER</p></div></div><div class="metrics"><div><strong>01</strong><span>New department</span></div><div><strong>06</strong><span>People to prepare</span></div><div><strong>0</strong><span>Prior industry experience</span></div></div>`,btn('Enter the experience'));n='Ed, this began inside your company. You created the first real B D C department for Checkmate Holding Group in Panama. Vianka and five new agents needed to inherit cabinet and countertop knowledge immediately.'}
if(s==='assessment'){h=shell('Executive Assessment','How much company intelligence disappears when the right person leaves?',`<div class="choices">${['Too much — judgment still lives mainly inside people.','Some — processes exist, but execution depends on who is present.','Very little — knowledge is governed, teachable and inherited.'].map((x,i)=>`<button data-answer="${x}"><em>0${i+1}</em><b>${x.split(' — ')[0]}</b><span>${x.split(' — ')[1]}</span></button>`).join('')}</div>`);n='How much company intelligence disappears when the right person leaves?'}
if(s==='mri'){h=shell('Enterprise MRI','The problem is not missing information. It is disconnected intelligence.',`<div class="mri"><div class="orbit"><div>ED'S<br>INTENT</div>${['People','Manuals','Systems','Departments','Companies'].map(x=>`<span>${x}</span>`).join('')}</div><div class="signals"><div><b>Knowledge dependency</b><strong>HIGH</strong><p>Critical judgement is difficult to inherit.</p></div><div><b>Training distance</b><strong>EXTENDED</strong><p>New people must find and interpret disconnected material.</p></div><div><b>Leadership repetition</b><strong>RECURRING</strong><p>The same standards must be retaught.</p></div></div></div>`,btn('Show me the proof'));n='The problem is not missing information. It is disconnected intelligence.'}
if(s==='origin'){h=shell('The real build','A binder could not create the department Ed needed.',`<p class="lead">The BDC Operating System converted Darren’s sales knowledge and Ed’s company standards into infrastructure Vianka and the agents could actually use.</p><div class="flow">${[['Product knowledge','CAPTURED'],['Customer conversations','STANDARDISED'],['Manager coaching','GOVERNED'],['Objections','ROUTED'],['Future hires','INHERITABLE']].map(x=>`<div><span>${x[0]}</span><b>${x[1]}</b></div>`).join('')}</div>`,btn('Open the living manual'));n='A binder could not create the department you needed. The B D C Operating System turned operating knowledge into infrastructure.'}
if(s==='manual'){h=shell('Proof of execution','This is not a PDF. It is a living operating surface.',`<p class="sub">Search it. Move between manuals. Keep the agent inside the work.</p>${manual(state.manual)}`,btn('Let Ed teach the system'));n='This is not a P D F. It is a living operating surface.'}
if(s==='contribution'){h=shell('Executive Contribution','When a customer says, “I’m just looking,” what should every future representative understand?',`<textarea id="contribution" placeholder="Enter the standard you want every future representative to inherit.">${esc(state.contribution)}</textarea><p class="truth">DEMONSTRATION MODE · YOUR RESPONSE IS SAVED LOCALLY · NO PRODUCTION RECORD IS CHANGED</p>`,btn('Route my judgement','route','xen'));n='Now teach your company something. What should every future representative understand when a customer says I am just looking?'}
if(s==='propagate'){h=shell('Visible Propagation','One approved decision. Every related layer learns.',`<div class="quote">“${esc(state.contribution||'Help the customer without pressure and earn the next step through usefulness.')}”</div><div class="flow">${[['Agent guidance','UPDATED'],['Manager coaching','INHERITED'],['Training certification','ALIGNED'],['Call quality rubric','MEASURE ADDED'],['Future hires','INHERITED'],['Executive memory','ATTRIBUTED TO ED']].map(x=>`<div><span>${x[0]}</span><b>${x[1]}</b></div>`).join('')}</div>`,btn('Reveal what Xen is','next','xen'));n='One approved decision. Every related layer learns.'}
if(s==='reveal'){h=`<section class="scene reveal"><div class="halo"><div>X</div></div><div class="kicker">THE REVEAL</div><h1>This manual is not actually a manual.</h1><p class="lead">It is the first living organ of a company capable of remembering, teaching, operating and improving itself.</p><div class="brandline">XEN · THE OPERATING SYSTEM FOR DESIGNING LIVING COMPANIES</div><div class="actions">${btn('Build the executive summary')}</div></section>`;n='This manual is not actually a manual. It is the first living organ of a company capable of remembering, teaching, operating and improving itself.'}
if(s==='summary'){h=shell('Executive Summary','The BDC system proves something much larger.',`<div class="summary"><section><span>Executive observation</span><p>${esc(state.answer||'Critical judgement remains dependent on the people who currently hold it.')}</p></section><section><span>Proof demonstrated</span><p>A live operating publication was searched, taught, governed and propagated.</p></section><section><span>Strategic implication</span><p>The same architecture can preserve Ed’s intent across departments and every Checkmate company—without replacing Checkmate 1 before the evidence defines the right relationship.</p></section></div><div class="bigq">What if every company you own could inherit what makes your best company work?</div>`,btn('Define the second meeting'));n='The B D C system proves something much larger. What if every company you own could inherit what makes your best company work?'}
if(s==='close'){h=shell('Executive Premiere Complete','The BDC Operating System was the proof. The Living Company is the opportunity.',`<div class="closegrid"><div><span>OWNER</span><b>Edward · Checkmate Holding Group</b></div><div><span>ARCHITECT</span><b>Darren · Xen creator and operating-system architect</b></div><div><span>NEXT MOVE</span><b>Select one Checkmate company or department for a Living Company Blueprint.</b></div></div><div class="seal">XEI-001 · XVS BRITISH VOICE · DIAMOND EXECUTIVE EXPERIENCE</div>`,btn('Replay','restart','ghost'));n='The B D C Operating System was the proof. The Living Company is the opportunity.'}
$('#stage').innerHTML=h;bind();chrome();setTimeout(()=>speak(n),350)}
function chrome(){const p=state.scene/(scenes.length-1)*100;$('#progress').style.width=p+'%';$('#sceneCount').textContent=`${String(state.scene+1).padStart(2,'0')} / ${String(scenes.length).padStart(2,'0')}`;$('#voice').textContent=state.voice?'XVS · British Voice On':'XVS · Voice Off';$('#back').disabled=state.scene===0}
function next(){if(state.scene<scenes.length-1){state.scene++;save();render()}}function back(){if(state.scene){state.scene--;save();render()}}
function bind(){$('#next')?.addEventListener('click',next);$('#restart')?.addEventListener('click',()=>{localStorage.removeItem(KEY);state={...defaults};render()});document.querySelectorAll('[data-answer]').forEach(x=>x.onclick=()=>{state.answer=x.dataset.answer;save();next()});document.querySelectorAll('[data-manual]').forEach(x=>x.onclick=()=>{state.manual=x.dataset.manual;save();render()});$('#search')?.addEventListener('input',e=>document.querySelectorAll('.line').forEach(x=>x.hidden=e.target.value&&!x.dataset.search.includes(e.target.value.toLowerCase())));$('#contribution')?.addEventListener('input',e=>{state.contribution=e.target.value;save()});$('#route')?.addEventListener('click',()=>{state.contribution=$('#contribution').value.trim()||'Help the customer without pressure and earn the next step through usefulness.';save();next()})}
$('#back').onclick=back;$('#home').onclick=()=>{state.scene=0;save();render()};$('#voice').onclick=()=>{state.voice=!state.voice;save();render()};document.onkeydown=e=>{if(e.key==='ArrowLeft')back();if(e.key==='ArrowRight'&&!/INPUT|TEXTAREA/.test(document.activeElement.tagName))next()};speechSynthesis.onvoiceschanged=()=>{};render();