const VERSION='1.0.0-gold-master';
const KEY='xei001.ed.session';
const manuals={
 'XBM-101':{title:'BDC Agent Field Guide',version:'1.0',section:'Customer Conversation Standard',content:['Understand before persuading.','Reduce pressure, clarify intent, educate accurately, and earn the next step.','Record the customer’s objective, concern, timeframe, decision-makers, and agreed follow-up in the CRM.']},
 'XBM-102':{title:'BDC Manager Operating Manual',version:'1.0',section:'Coaching & Quality Standard',content:['Coach observable behaviors, not personality.','Review whether the representative listened, clarified, educated, confirmed, and documented the interaction.']},
 'XBM-103':{title:'BDC Objection Playbook',version:'1.0',section:'“I’m Just Looking”',content:['Listen without interrupting.','Acknowledge without pressure.','Clarify what the customer hopes to learn.','Educate with the smallest useful amount of accurate information.','Offer a useful next step and let the customer choose.']},
 'XBM-104':{title:'BDC Script Playbook',version:'1.0',section:'Approved Customer Language',content:['“Absolutely. What are you hoping to learn while you look?”','“I can give you a quick starting point without putting pressure on you.”','“Would it help to compare styles, budget ranges, or the project process first?”']}
};
const scenes=['welcome','remember','assessment','intent','origin','family','read','question','route','approve','propagate','reveal','summary','legacy','company','department','blueprint','close'];
const defaults={scene:0,answers:{},intent:'',contribution:'',route:null,approved:false,company:'',department:'',voice:true,started:false,updatedAt:Date.now()};
let state=load();
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function load(){try{return {...defaults,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return {...defaults}}}
function save(){state.updatedAt=Date.now();localStorage.setItem(KEY,JSON.stringify(state));updateProgress()}
function updateProgress(){const p=Math.round((state.scene/(scenes.length-1))*100);$('#progress').style.width=p+'%';$('#sceneCount').textContent=`${state.scene+1} / ${scenes.length}`}
function speak(text){if(!state.voice||!('speechSynthesis'in window))return; speechSynthesis.cancel(); const u=new SpeechSynthesisUtterance(text);u.rate=.94;u.pitch=1;u.volume=.92;speechSynthesis.speak(u)}
function classify(t){const x=t.toLowerCase();if(/just looking|objection|pressure|not interested|expensive|think about|price/.test(x))return 'XBM-103';if(/say|script|phrase|word|opening|follow/.test(x))return 'XBM-104';if(/coach|manager|quality|score|review/.test(x))return 'XBM-102';return 'XBM-101'}
function shell(kicker,title,body,actions=''){return `<section class="scene"><div class="kicker">${kicker}</div><h1>${title}</h1>${body}<div class="actions">${actions}</div></section>`}
function button(label,id='next',kind='primary'){return `<button class="btn ${kind}" id="${id}">${label}</button>`}
function manualViewer(id,focus=false){const m=manuals[id];return `<div class="manual-shell" id="manualTarget"><aside class="manual-nav"><div class="status">CANONICAL · v${m.version}</div><h3>${m.title}</h3><input id="manualSearch" aria-label="Search manual" placeholder="Search this manual"><button data-manual="XBM-101">Agent</button><button data-manual="XBM-102">Manager</button><button data-manual="XBM-103">Objections</button><button data-manual="XBM-104">Scripts</button><div class="meta">Living Document<br>Executive contributor: Edward<br>Inherited by training, coaching, QA and future-hire systems.</div></aside><article class="manual-page"><div class="kicker">${id} · ${m.section}</div><h2>${m.section}</h2>${m.content.map((x,i)=>`<p class="manual-line" data-search="${esc(x.toLowerCase())}"><b>${String(i+1).padStart(2,'0')}</b>${esc(x)}</p>`).join('')}${focus?`<div class="revision" id="revision"><div class="kicker">Proposed evolution · Executive contribution</div><h3>${esc(state.contribution)}</h3><p><strong>Why here:</strong> Xen classified this as ${m.title}, ${m.section}, because the instruction governs ${id==='XBM-103'?'a customer objection and the pressure-reduction response':'the operating behavior represented by this section'}.</p><p><strong>Operational impact:</strong> Future agents inherit the response; managers coach it; QA measures it; training certifies it.</p></div>`:''}</article></div>`}
function render(){try{speechSynthesis?.cancel();const name=scenes[state.scene];let html='';let narration='';
 if(name==='welcome'){html=shell('Private Executive Premiere','Ed, meet Xen.',`<p class="lead">A self-guided executive experience created around Checkmate Holding Group and the future of building Living Companies.</p><p>Your progress is saved automatically. A phone call, refresh, or interruption will not make you start over.</p>`,button('Let Xen Guide Me','start'));narration='Welcome, Ed. Darren asked me to guide you personally. This is not a software demonstration. It is an experience of what a company can become.'}
 if(name==='remember'){html=shell('The first question','Should a company remember?',`<p class="lead">What its people learn. What its leaders decide. What makes it successful.</p>`,button('Yes. It should.'));narration='Should a company remember? Not files. Not data. What its people learn, what its leaders decide, and what makes it successful.'}
 if(name==='assessment'){html=shell('Living Company Assessment','How much critical judgment still lives inside people?',`<div class="choice-grid">${[['Too much','The company loses knowledge when people leave.'],['Some','Core processes remain, but judgment varies.'],['Very little','Knowledge is captured, governed and inherited.']].map((x,i)=>`<button class="choice" data-answer="${i}"><b>${x[0]}</b><span>${x[1]}</span></button>`).join('')}</div>`);narration='Choose the answer that is most true today. There is no ideal answer.'}
 if(name==='intent'){html=shell('Executive intent','What should every company you own inherit from you?',`<p class="lead">Use your own words. On iPhone, tap the field, then tap the microphone on the Apple keyboard.</p><textarea id="intent" placeholder="Standards, judgment, integrity, urgency, customer care...">${esc(state.intent)}</textarea><p class="hint">Your words are preserved immediately and will shape the Executive Summary.</p>`,button('Let Xen Remember This','capture'));narration='Tell me what every company you own should inherit from you. On an iPhone, tap the field and use the microphone on the Apple keyboard.'}
 if(name==='origin'){html=shell('The true origin','There was no BDC department.',`<div class="timeline"><p><b>01</b> Marisol was a virtual assistant used as the de facto BDC.</p><p><b>02</b> Vianka Gomez became the first actual BDC Manager.</p><p><b>03</b> Vianka and five Panamanian agents had no kitchen cabinet or countertop sales experience.</p><p><b>04</b> Operational knowledge had to become repeatable, inheritable company infrastructure.</p></div>`,button('See what was built'));narration='There was no B D C department. Marisol was a virtual assistant used as the de facto B D C. Vianka Gomez became the first actual B D C Manager, leading five Panamanian agents without cabinet or countertop sales experience.'}
 if(name==='family'){html=shell('Real Checkmate assets','The BDC Living Publication Family',`<p class="lead">These are commercial operating assets—not mockups. Open one without leaving this experience.</p><div class="manual-grid">${Object.entries(manuals).map(([id,m])=>`<button class="manual-card" data-open="${id}"><span>${id} · CANONICAL</span><h3>${m.title}</h3><p>${m.section}</p></button>`).join('')}</div>`,button('Continue to guided reading'));narration='The manuals are the first proof. Operational knowledge became a publication family that future people can inherit.'}
 if(name==='read'){html=shell('Embedded Living Manual Runtime','Read the actual operating content.',`<p class="hint">Search, switch manuals, and read without leaving the premiere. Xen will remain silent while you read.</p>${manualViewer('XBM-103')}`,button('I’ve read it'));narration='';}
 if(name==='question'){html=shell('Live Executive Contribution','When a customer says, “I’m just looking,” what should every future BDC representative understand or do?',`<textarea id="contribution" placeholder="Tap here, then use the Apple keyboard microphone or type your answer.">${esc(state.contribution)}</textarea><p class="hint">Your response is saved as you enter it. Xen will route it to the correct canonical manual, chapter, and section.</p>`,button('Route My Answer','route'));narration='Now teach the company something. Tell me what every future representative should understand or do when a customer says they are just looking.'}
 if(name==='route'){const id=state.route||classify(state.contribution);state.route=id;save();html=shell('Manual Router · Classified','Xen found the correct home.',`<p class="lead">Your answer belongs in <strong>${manuals[id].title}</strong>, section <strong>${manuals[id].section}</strong>.</p><p class="mobile-guide">The proposed revision is farther down this screen. Xen has scrolled you to it. Read it, then press <b>Approve Evolution</b>.</p>${manualViewer(id,true)}`,button('Approve Evolution','approve','green'));narration=`I routed your answer to ${manuals[id].title}, ${manuals[id].section}. The proposed revision is farther down the screen. I am scrolling you to it now. Read it, then press Approve Evolution.`;setTimeout(()=>$('#revision')?.scrollIntoView({behavior:'smooth',block:'center'}),450)}
 if(name==='approve'){html=shell('Executive approval','Your judgment is becoming infrastructure.',`<div class="approval"><div>Version</div><b>${manuals[state.route].version} → 1.1 proposed</b><div>Executive contributor</div><b>Edward</b><div>Destination</div><b>${state.route} · ${manuals[state.route].section}</b><div>Approved principle</div><b>${esc(state.contribution)}</b></div>`,button('Propagate Across the Company'));narration='Your contribution has been approved with version and executive attribution.'}
 if(name==='propagate'){html=shell('Visible propagation','One decision. Every related layer learns.',`<div class="propagation">${[['BDC Agent manual','Updated'],['BDC Manager coaching','Inherited'],['Objection certification','Aligned'],['Call QA rubric','Measure added'],['New-hire training','Inherited'],['Executive knowledge layer','Remembered']].map(x=>`<div><span>${x[0]}</span><b>${x[1]}</b></div>`).join('')}</div>`,button('Reveal What Xen Is'));narration='The approved decision now propagates across the agent manual, manager coaching, certification, quality assurance, future hires, and executive memory.'}
 if(name==='reveal'){html=shell('The category','Xen is the operating system for designing Living Companies.',`<p class="lead">Memory becomes infrastructure. Infrastructure learns. Leadership compounds across the enterprise.</p>`,button('Build My Executive Summary'));narration='This is the distinction. Xen is the operating system for designing Living Companies.'}
 if(name==='summary'){const intent=state.intent||'your standards and judgment';html=shell('Prepared from this session','Executive Summary',`<div class="summary"><h3>Executive observation</h3><p>Checkmate’s ambition is ahead of its institutional memory. Critical judgment still travels through people more than governed infrastructure.</p><h3>What you want inherited</h3><p>${esc(intent)}</p><h3>Proof created today</h3><p>Your instruction—“${esc(state.contribution)}”—was routed into ${manuals[state.route].title}, approved with executive attribution, and propagated into coaching, training, QA and future-hire inheritance.</p><h3>Strategic opportunity</h3><p>The BDC family proves the method. Xen can now apply the same Living Company architecture across Checkmate’s companies and departments.</p></div>`,button('Continue'));narration='This Executive Summary was generated from your real answers and the contribution you placed into the B D C system.'}
 if(name==='legacy'){html=shell('Legacy reflection','What should remain true after today’s leaders are gone?',`<p class="lead">A Living Company does not merely preserve documents. It preserves judgment, intent, standards, learning and the ability to evolve responsibly.</p>`,button('Choose Where Xen Enters First'));narration='Legacy is not what a leader remembers. It is what the company can still practice after the leader is no longer in the room.'}
 if(name==='company'){const companies=['Artcraft Kitchen & Design','A Cut Above Design Stone & Marble','B & G Construction / Restoration','Elite Siding & Roofing','Elite Outdoor Designs','Checkmate Adjustment Services','Biotile Panamá','Renfro Pro'];html=shell('Executive selection','Which Checkmate company should Xen enter first?',`<div class="choice-grid">${companies.map(x=>`<button class="choice company" data-company="${esc(x)}"><b>${x}</b><span>Build the first Living Company blueprint here.</span></button>`).join('')}</div>`);narration='Choose the company where Xen should begin the first Living Company blueprint.'}
 if(name==='department'){const deps=['BDC / Sales Development','Sales','Operations','Production / Installation','Marketing','Purchasing','Finance','Leadership'];html=shell('Department selection',`Where inside ${esc(state.company)} should Xen begin?`,`<div class="choice-grid">${deps.map(x=>`<button class="choice department" data-department="${x}"><b>${x}</b><span>Map memory, execution and evolution.</span></button>`).join('')}</div>`);narration='Now choose the department where Xen should begin.'}
 if(name==='blueprint'){html=shell('Living Company Blueprint Session','The next meeting has a real operating mandate.',`<div class="summary"><p><b>Company:</b> ${esc(state.company)}</p><p><b>Department:</b> ${esc(state.department)}</p><p><b>Executive inheritance target:</b> ${esc(state.intent)}</p><hr><p>The session will produce an Enterprise Memory Map, Knowledge Dependency Analysis, 90-Day Living Department Blueprint, and the first Living Infrastructure prototype.</p></div>`,button('Confirm Blueprint Session','confirm','green'));narration='Your Blueprint Session is now defined around the company and department you selected.'}
 if(name==='close'){html=shell('Executive Premiere Complete','Every company grows. Very few remember.',`<p class="lead">The companies that lead the future will be Living Companies.</p><p>Today Xen remembered one executive decision. Next, Xen begins operating inside <strong>${esc(state.company)}</strong>, starting with <strong>${esc(state.department)}</strong>.</p><div class="seal">XEI-001 · XENESIS EXECUTIVE PREMIERE<br>GOLD MASTER RELEASE CANDIDATE · ${VERSION}</div>`,button('Restart Experience','restart','ghost'));narration='Thank you, Ed. Today Xen remembered one decision. Next, Xen begins operating inside the ecosystem.'}
 $('#stage').innerHTML=html;bind();updateProgress();if(narration)speak(narration)}catch(err){console.error(err);$('#stage').innerHTML=shell('Recovery mode','Xen protected your session.',`<p>Your progress is safe. Press recover to restore the last complete scene.</p><pre>${esc(err.message)}</pre>`,button('Recover','recover'))}}
function next(){state.scene=Math.min(state.scene+1,scenes.length-1);save();render();scrollTo({top:0,behavior:'smooth'})}
function bind(){document.querySelectorAll('#next').forEach(b=>b.onclick=next);$('#start')?.addEventListener('click',()=>{state.started=true;next()});$('#capture')?.addEventListener('click',()=>{state.intent=$('#intent').value.trim();save();next()});$('#intent')?.addEventListener('input',e=>{state.intent=e.target.value;save()});$('#contribution')?.addEventListener('input',e=>{state.contribution=e.target.value;save()});$('#route')?.addEventListener('click',()=>{state.contribution=$('#contribution').value.trim()||'Reduce pressure, understand what the customer wants to learn, educate them, and earn the next step.';state.route=classify(state.contribution);next()});$('#approve')?.addEventListener('click',()=>{state.approved=true;next()});$('#confirm')?.addEventListener('click',next);$('#restart')?.addEventListener('click',()=>{localStorage.removeItem(KEY);state={...defaults};render()});$('#recover')?.addEventListener('click',render);document.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{state.answers.assessment=+b.dataset.answer;next()});document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>{state.lastManual=b.dataset.open;state.scene=scenes.indexOf('read');save();render()});document.querySelectorAll('[data-manual]').forEach(b=>b.onclick=()=>{const host=$('#manualTarget');host.outerHTML=manualViewer(b.dataset.manual);bind()});document.querySelectorAll('[data-company]').forEach(b=>b.onclick=()=>{state.company=b.dataset.company;next()});document.querySelectorAll('[data-department]').forEach(b=>b.onclick=()=>{state.department=b.dataset.department;next()});$('#manualSearch')?.addEventListener('input',e=>document.querySelectorAll('.manual-line').forEach(p=>p.hidden=!p.dataset.search.includes(e.target.value.toLowerCase())))}
$('#back').onclick=()=>{state.scene=Math.max(0,state.scene-1);save();render()};$('#voice').onclick=()=>{state.voice=!state.voice;speechSynthesis?.cancel();$('#voice').textContent=`Voice: ${state.voice?'On':'Off'}`;save()};window.addEventListener('error',e=>console.error('XEI boundary',e.error));window.addEventListener('unhandledrejection',e=>console.error('XEI rejection',e.reason));document.addEventListener('visibilitychange',save);window.addEventListener('pagehide',save);render();