import {createLivingManualService,InMemoryAuditStore} from './alpha-one/living-manual-service.js';

const KEY='xei-series-v1';
const manualContext={actorId:'employee-demo',tenantId:'checkmate-demo',roles:['employee'],permissions:['manual:read','practice:start','practice:score']};
const manualService=fetch('content/alpha-one-bdc-approved-sources.json').then(response=>{if(!response.ok)throw new Error('approved_source_unavailable');return response.json()}).then(fixture=>({runtime:createLivingManualService({sources:fixture.sources,auditStore:new InMemoryAuditStore()}),rubric:fixture.practiceRubric}));
const modules=[
{id:'XEI-002',name:'Living Company Blueprint Session',purpose:'Diagnose one company and department, expose memory risk, and create the first 90-day Living Department blueprint.'},
{id:'XEI-003',name:'Executive Transformation Proposal',purpose:'Convert the blueprint into an executive mandate, commercial scope, governance model, and measurable investment case.'},
{id:'XEI-004',name:'First Living Department Deployment',purpose:'Launch the first department runtime with owners, operating cadence, controls, milestones, and acceptance criteria.'},
{id:'XEI-005',name:'Living Manual Runtime',purpose:'Turn approved operating knowledge into searchable, evolving, inheritable manuals inside the work experience.'},
{id:'XEI-006',name:'Executive Memory & Decision Intelligence',purpose:'Capture leadership intent, decisions, rationale, dependencies, and future review triggers as governed enterprise memory.'},
{id:'XEI-007',name:'Enterprise Propagation Engine',purpose:'Propagate approved improvements across manuals, coaching, QA, training, systems, and related companies with controlled inheritance.'},
{id:'XEI-008',name:'Living Company Dashboard',purpose:'Show readiness, risk, execution, learning, propagation, and operating health in one executive view.'},
{id:'XEI-009',name:'Executive Command Center',purpose:'Give leadership one intent-first command surface for priorities, decisions, interventions, and enterprise navigation.'},
{id:'XEI-010',name:'Enterprise Rollout & Multi-Company Orchestration',purpose:'Scale Xen across the Checkmate ecosystem with sequencing, shared services, local identity, governance, and continuous evolution.'}
];
const defaults={screen:'map',index:0,completed:[],company:'',department:'',leaderIntent:'',memoryRisk:'',priorityOutcome:'',budget:'',sponsor:'Edward',proposalApproved:false,deploymentOwner:'',manualStandard:'',decision:'',propagationApproved:false,rolloutWave:'',notes:{},updatedAt:null};
let state=load();
const stage=document.querySelector('#seriesStage'),progress=document.querySelector('#seriesProgress'),back=document.querySelector('#seriesBack'),next=document.querySelector('#seriesNext'),home=document.querySelector('#seriesHome'),resume=document.querySelector('#resumeSeries'),toast=document.querySelector('#seriesToast');
function load(){try{return {...defaults,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return {...defaults}}}
function save(){state.updatedAt=new Date().toISOString();localStorage.setItem(KEY,JSON.stringify(state));updateProgress()}
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function notify(t){toast.textContent=t;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),1800)}
function updateProgress(){const pct=Math.round((state.completed.length/modules.length)*100);progress.style.width=`${pct}%`}
function complete(id){if(!state.completed.includes(id))state.completed.push(id);save();notify(`${id} output preserved`)}
function field(id,label,value='',type='text',placeholder=''){return `<div class="field"><label for="${id}">${label}</label>${type==='textarea'?`<textarea id="${id}" placeholder="${placeholder}">${esc(value)}</textarea>`:`<input id="${id}" type="${type}" value="${esc(value)}" placeholder="${placeholder}">`}</div>`}
function bindFields(ids){ids.forEach(id=>{const el=document.querySelector(`#${id}`);if(el)el.addEventListener('input',()=>{state[id]=el.value;save()})})}
function map(){state.screen='map';save();stage.innerHTML=`<section class="hero"><span class="eyebrow">XEI-001 established belief. The series now converts belief into enterprise operation.</span><h1 class="display">Build the first Living Company ecosystem.</h1><p class="lead">Each module creates a governed executive output and passes it forward. Progress survives refreshes, interruptions, and device changes when browser storage is retained.</p><div class="grid">${modules.map((m,i)=>`<article class="card"><button data-open="${i}"><span class="status">${state.completed.includes(m.id)?'Complete':'Ready'} · ${m.id}</span><h3>${m.name}</h3><p>${m.purpose}</p></button></article>`).join('')}</div></section>`;document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>open(Number(b.dataset.open)));back.disabled=true;next.textContent='Open Next Module';next.disabled=false;next.onclick=()=>open(Math.min(state.completed.length,modules.length-1));stage.focus()}
function shell(m,body){return `<section><span class="eyebrow">${m.id} · Production Executive Runtime</span><h1>${m.name}</h1><p class="lead">${m.purpose}</p>${body}</section>`}
function open(i){state.index=i;state.screen='module';save();const m=modules[i];const renderers=[blueprint,proposal,deployment,manualRuntime,memory,propagation,dashboard,command,rollout];stage.innerHTML=shell(m,renderers[i](m));bind(i,m);back.disabled=false;back.onclick=()=>i?open(i-1):map();next.disabled=false;next.textContent=i===modules.length-1?'Complete Series':'Continue';next.onclick=()=>{complete(m.id);i===modules.length-1?finale():open(i+1)};stage.focus();window.scrollTo({top:0,behavior:'smooth'})}
function blueprint(){return `<div class="form-grid">${field('company','Selected Checkmate company',state.company,'text','Artcraft Kitchen & Design')}${field('department','First department',state.department,'text','BDC, Sales, Operations…')}${field('leaderIntent','What must this company inherit from leadership?',state.leaderIntent,'textarea','Standards, judgment, customer philosophy, urgency…')}${field('memoryRisk','Where can knowledge currently walk out?',state.memoryRisk,'textarea','People, decisions, vendor knowledge, estimating, follow-up…')}${field('priorityOutcome','90-day measurable outcome',state.priorityOutcome,'textarea','The operating result Xen must create first')}${field('sponsor','Executive sponsor',state.sponsor)}</div><div class="panel"><span class="tag">Blueprint output</span><div class="timeline"><div class="panel"><span class="num">01</span><div><h3>Protect</h3><p>Map knowledge dependency and continuity risk inside ${esc(state.company||'the selected company')}.</p></div></div><div class="panel"><span class="num">02</span><div><h3>Convert</h3><p>Translate executive intent into owned standards, workflows, manuals, training and controls.</p></div></div><div class="panel"><span class="num">03</span><div><h3>Multiply</h3><p>Measure the first department and prepare controlled inheritance across Checkmate.</p></div></div></div></div>`}
function proposal(){return `<div class="form-grid">${field('budget','Investment range or commercial boundary',state.budget,'text','Pilot budget, monthly mandate, or value threshold')}${field('priorityOutcome','Executive outcome promised',state.priorityOutcome,'textarea')}${field('sponsor','Executive sponsor',state.sponsor)}<div class="panel"><span class="tag">Mandate</span><h3>${esc(state.company||'Selected company')} · ${esc(state.department||'Selected department')}</h3><p>Xen will reduce dependency on individual memory, convert approved leadership judgment into infrastructure, and produce a measurable ${esc(state.priorityOutcome||'90-day operating outcome')}.</p><label><input id="proposalApproved" type="checkbox" ${state.proposalApproved?'checked':''}> Approve transformation mandate</label></div></div><div class="grid"><div class="card"><span class="tag">Business case</span><h3>Continuity</h3><p>Protect revenue, customer experience and execution quality from knowledge loss.</p></div><div class="card"><span class="tag">Business case</span><h3>Speed</h3><p>Reduce the distance between executive intent and frontline execution.</p></div><div class="card"><span class="tag">Business case</span><h3>Scale</h3><p>Make successful methods inheritable across companies without erasing local identity.</p></div></div>`}
function deployment(){return `<div class="form-grid">${field('deploymentOwner','Living Department owner',state.deploymentOwner,'text','Named operating owner')}${field('priorityOutcome','Deployment acceptance outcome',state.priorityOutcome,'textarea')}</div><div class="timeline"><div class="panel"><span class="num">01</span><div><h3>Days 1–15 · Observe</h3><p>Capture actual work, decisions, handoffs, failure points, tools and undocumented judgment.</p></div></div><div class="panel"><span class="num">02</span><div><h3>Days 16–45 · Build</h3><p>Create the first governed workflows, Living Documents, coaching loops and quality controls.</p></div></div><div class="panel"><span class="num">03</span><div><h3>Days 46–90 · Operate</h3><p>Run the department through Xen, measure adoption and outcomes, diagnose gaps, then release the replication package.</p></div></div></div>`}
function manualRuntime(){return `<div class="truth-banner"><strong>DEMONSTRATION DATA</strong><span>Governed Alpha One proof · not a live Checkmate deployment</span></div><div class="manual-ai panel"><span class="tag">Ask Xen · Living Manual Guide</span><h3>Ask, translate, or practice.</h3><label for="manualQuestion">Employee question</label><textarea id="manualQuestion" placeholder="How do I schedule an appointment?"></textarea><div class="actions"><button class="btn primary" id="askManual" type="button">Ask Xen</button><button class="btn" id="askManualSpanish" type="button">Explícamelo en español</button><button class="btn" id="startPractice" type="button">Practice a hesitant customer</button></div><div id="manualAnswer" class="manual-answer" role="status" aria-live="polite"><p>Answers cite the approved source and version. Missing knowledge escalates to the manual owner.</p></div></div>${field('manualStandard','Propose one operating-standard improvement',state.manualStandard,'textarea','Example: When a customer says “I’m just looking,” reduce pressure, educate first, and earn the next step.')}<div class="panel"><span class="tag">Proposed routing preview · approval required</span><h3>${routeManual(state.manualStandard).id} · ${routeManual(state.manualStandard).section}</h3><p><strong>Existing intent:</strong> Customer conversations must build trust and move toward a useful next step.</p><p class="accent"><strong>Proposed evolution:</strong> ${esc(normalize(state.manualStandard||'Approved leadership guidance will be converted into a clear representative standard.'))}</p><div class="propagation"><div><span>Agent manual</span><em>Review pending</em></div><div><span>Manager coaching guide</span><em>Review pending</em></div><div><span>Certification scenario</span><em>Not generated</em></div><div><span>QA rubric</span><em>Not changed</em></div></div></div>`}
function memory(){return `${field('decision','Executive decision, rationale, or operating principle to remember',state.decision,'textarea','State the decision and why it matters.')}<div class="grid"><div class="card"><span class="tag">Decision record</span><h3>Intent</h3><p>${esc(state.decision||'Awaiting executive decision.')}</p></div><div class="card"><span class="tag">Governance</span><h3>Review trigger</h3><p>Review when performance, market conditions, ownership, customer behavior, or operating dependencies materially change.</p></div><div class="card"><span class="tag">Inheritance</span><h3>Future use</h3><p>Expose the decision to authorized leaders, relevant manuals, workflows, coaching and future strategic reviews.</p></div></div>`}
function propagation(){return `<div class="panel"><span class="tag">Controlled inheritance from ${esc(state.department||'the first department')}</span><h3>One approved improvement. Multiple governed effects.</h3><div class="propagation"><div><span>Operating manual</span><em>Versioned</em></div><div><span>Manager coaching</span><em>Updated</em></div><div><span>Training and certification</span><em>Regenerated</em></div><div><span>Quality assurance</span><em>Aligned</em></div><div><span>Executive memory</span><em>Recorded</em></div><div><span>Related companies</span><em>Review required</em></div></div><label><input id="propagationApproved" type="checkbox" ${state.propagationApproved?'checked':''}> Authorize controlled propagation</label></div>`}
function dashboard(){const readiness=Math.min(94,35+state.completed.length*7+(state.company?5:0)+(state.priorityOutcome?5:0));return `<div class="grid"><div class="card"><span class="tag">Living Company readiness</span><h3 class="display">${readiness}</h3><p>Current governed readiness baseline.</p></div><div class="card"><span class="tag">Primary company</span><h3>${esc(state.company||'Not selected')}</h3><p>${esc(state.department||'Department pending')}</p></div><div class="card"><span class="tag">Evolution status</span><h3>${state.completed.length} / 9</h3><p>Executive modules completed.</p></div></div><div class="panel"><div class="metric"><span>Executive intent captured</span><b>${state.leaderIntent?'Yes':'Pending'}</b></div><div class="metric"><span>Memory risk mapped</span><b>${state.memoryRisk?'Yes':'Pending'}</b></div><div class="metric"><span>Transformation mandate</span><b>${state.proposalApproved?'Approved':'Pending'}</b></div><div class="metric"><span>Propagation authority</span><b>${state.propagationApproved?'Approved':'Controlled'}</b></div></div>`}
function command(){return `<div class="grid"><div class="card"><span class="tag">Executive GPS</span><h3>Protect</h3><p>${esc(state.memoryRisk||'Identify the most exposed knowledge dependency.')}</p></div><div class="card"><span class="tag">Executive GPS</span><h3>Achieve</h3><p>${esc(state.priorityOutcome||'Define the first measurable enterprise outcome.')}</p></div><div class="card"><span class="tag">Executive GPS</span><h3>Expand</h3><p>Use the first proven Living Department as the replication standard across Checkmate.</p></div></div><div class="panel"><span class="tag">Current executive command</span><h3>Enter ${esc(state.company||'the selected company')} through ${esc(state.department||'the selected department')}.</h3><p>Owner: ${esc(state.deploymentOwner||state.sponsor||'Executive assignment pending')}. Govern every change through evidence, approval, versioning, propagation controls and measurable operating outcomes.</p></div>`}
function rollout(){return `<div class="form-grid">${field('rolloutWave','First multi-company rollout wave',state.rolloutWave,'textarea','List the next companies or shared functions in sequence.')}</div><div class="timeline"><div class="panel"><span class="num">01</span><div><h3>Prove</h3><p>Finish the first Living Department and certify the operating model.</p></div></div><div class="panel"><span class="num">02</span><div><h3>Package</h3><p>Separate universal Checkmate standards from company-specific identity and execution.</p></div></div><div class="panel"><span class="num">03</span><div><h3>Propagate</h3><p>Deploy by value, readiness and risk—not by organizational chart order.</p></div></div><div class="panel"><span class="num">04</span><div><h3>Orchestrate</h3><p>Operate the portfolio through shared executive intelligence, local company autonomy and continuous evolution.</p></div></div></div>`}
function routeManual(t=''){const x=t.toLowerCase();if(/objection|just looking|expensive|think about|not interested|price/.test(x))return{id:'XBM-103',section:'Customer Objection Response'};if(/script|say|phrase|opening|follow.?up/.test(x))return{id:'XBM-104',section:'Approved Customer Language'};if(/manager|coach|quality|review|score/.test(x))return{id:'XBM-102',section:'Coaching & Quality Standard'};return{id:'XBM-101',section:'Agent Mission & Operating Standard'}}
function normalize(t){const x=t.trim().replace(/[.]+$/,'');return x?`Representatives will ${x.charAt(0).toLowerCase()+x.slice(1)}. Managers will coach it, quality assurance will measure it, and future hires will inherit it.`:'Approved leadership guidance will become a measurable operating standard.'}
function bind(i,m){const ids=['company','department','leaderIntent','memoryRisk','priorityOutcome','budget','sponsor','deploymentOwner','manualStandard','decision','rolloutWave'];bindFields(ids);['proposalApproved','propagationApproved'].forEach(id=>{const el=document.querySelector(`#${id}`);if(el)el.onchange=()=>{state[id]=el.checked;save()}});if(i===3)bindManualGuide()}
function bindManualGuide(){const question=document.querySelector('#manualQuestion'),answer=document.querySelector('#manualAnswer');const show=result=>{const citation=result.source?`${esc(result.source.title)} · ${esc(result.source.id)} v${esc(result.source.version)}`:'Escalation required · no approved source';answer.innerHTML=`<strong>${esc(result.dataLabel||'GOVERNED RESULT')}</strong><p>${esc(result.answer||result.opening)}</p><small>${citation}</small>`};const ask=async language=>{answer.innerHTML='<p>Xen is checking approved manual knowledge…</p>';try{const {runtime}=await manualService;show(await runtime.ask({context:manualContext,question:question.value||'appointment readiness',language}))}catch{answer.innerHTML='<strong>WARDEN ESCALATION</strong><p>The approved manual source is unavailable. No answer was generated.</p>'}};document.querySelector('#askManual').onclick=()=>ask('en');document.querySelector('#askManualSpanish').onclick=()=>ask('es');document.querySelector('#startPractice').onclick=async()=>{try{const {runtime,rubric}=await manualService;show(await runtime.startPractice({context:manualContext,scenario:'hesitant homeowner',rubric}))}catch{answer.innerHTML='<strong>WARDEN ESCALATION</strong><p>Practice could not start safely.</p>'}}}
function finale(){modules.forEach(m=>{if(!state.completed.includes(m.id))state.completed.push(m.id)});save();stage.innerHTML=`<section class="hero"><span class="eyebrow">XEI-001 through XEI-010 · Integrated Executive Series</span><h1 class="display">The premiere became an operating mandate.</h1><p class="lead">${esc(state.company||'The selected Checkmate company')} now has a continuous path from executive belief to blueprint, proposal, deployment, living manuals, governed memory, propagation, dashboard, command and multi-company orchestration.</p><div class="panel"><span class="tag">First Living Company mandate</span><h3>${esc(state.company||'Company selection required')} · ${esc(state.department||'Department selection required')}</h3><p><strong>Executive intent:</strong> ${esc(state.leaderIntent||'Capture required')}</p><p><strong>90-day outcome:</strong> ${esc(state.priorityOutcome||'Define required')}</p><p><strong>Deployment owner:</strong> ${esc(state.deploymentOwner||'Assign required')}</p><p><strong>Rollout wave:</strong> ${esc(state.rolloutWave||'Sequence after first proof')}</p></div><div class="actions"><button id="returnMap" class="btn primary">Review Series Map</button><button id="exportSummary" class="btn green">Export Executive Record</button></div></section>`;document.querySelector('#returnMap').onclick=map;document.querySelector('#exportSummary').onclick=exportRecord;next.disabled=true;back.disabled=false;back.onclick=()=>open(8)}
function exportRecord(){const record={program:'XEI Living Company Executive Series',version:'1.0.0',generatedAt:new Date().toISOString(),...state,modules:modules.map(m=>({...m,status:state.completed.includes(m.id)?'complete':'pending'}))};const blob=new Blob([JSON.stringify(record,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='XEI-Executive-Record.json';a.click();URL.revokeObjectURL(a.href)}
home.onclick=map;resume.onclick=()=>state.screen==='module'?open(state.index):map();window.addEventListener('pagehide',save);window.addEventListener('error',()=>{notify('Xen preserved the session. Use Resume to recover.')});window.addEventListener('unhandledrejection',()=>{notify('A module recovered without losing progress.')});updateProgress();state.screen==='module'?open(state.index):map();
